eureka:
  client:
    serviceUrl:
      defaultZone: http://appuser:1122233aaaaa@localhost:8761/eureka/

server:
  port: 6101
spring:
  application:
    name: client-service

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

hello: client-service is 6101, version is 1.0

