eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/

server:
  port: 6101
spring:
  application:
    name: client-service

hello: client-service is 6101, version is 1.0
  
