eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/

server:
  port: 6004
spring:
  application:
    name: gateway-server

hello: gateway-server is 6003, version is 1.0
  
