eureka:
  client:
    serviceUrl:
      defaultZone: http://appuser:1122233aaaaa@localhost:8761/eureka/

server:
  port: 6003
spring:
  application:
    name: zuul-server

hello: zuul-server is 6003, version is 1.0

